name: Run Shared Build and Push Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - "package.json"
      - "src/**"
      - "Dockerfile"
      - ".dockerignore"

jobs:
  build_and_push_to_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jabez007/create-express-template/.github/shared/version@master

      - uses: jabez007/docker-kitchen/.github/shared/docker@master
        with:
          push: true
          image-name: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          debug: ${{ vars.pipeline_debug }}
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

  build_and_push_to_ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required if push is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jabez007/create-express-template/.github/shared/version@master

      - uses: jabez007/docker-kitchen/.github/shared/ghcr@master
        with:
          push: true
          debug: ${{ vars.pipeline_debug }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
