name: Version
description: ''

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Run version script
      run: npm run version:short
      shell: bash
