name: Run Shared Build Workflow

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jabez007/create-express-template/.github/shared/version@development

      - uses: jabez007/aws-kubectl/.github/shared/docker@master
        with:
          debug: ${{ vars.pipeline_debug }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
