name: Run Shared Build Workflow

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  version_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: jabez007/create-express-template/.github/shared/version@master

      - uses: jabez007/docker-kitchen/.github/shared/docker@master
        with:
          image-name: ${{ github.event.repository.name }}
          debug: ${{ vars.pipeline_debug }}
