name: Run Shared Build and Push Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'
      - 'src/**'
      - 'Dockerfile'
      - '.dockerignore'

jobs:
  version_and_build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # required if push is true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jabez007/create-express-template/.github/shared/version@development

      - uses: jabez007/aws-kubectl/.github/shared/docker@master
        with:
          push: true
          debug: ${{ vars.pipeline_debug }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
