name: Run Shared Dry Run Workflow

on:
  push:
    branches:
      - development

jobs:
  dry_run_k8s:
    permissions:
      contents: read
      packages: write
    uses: jabez007/create-express-template/.github/workflows/shared.dry_run_k8s.yml@master
    secrets: inherit
