name: Run Shared Dry Run Workflow

on:
  push:
    branches:
      - development

jobs:
  dry_run_k8s:
    permissions:
      contents: read
    uses: jabez007/create-express-template/.github/workflows/shared.dry_run_k8s.yml@master
    with:
      env_files: .env , .env.development
    secrets: inherit
