name: Build and Push Docker Image to GHCR

on:
  workflow_call:
    inputs:
      platforms:
        type: string
        default: linux/amd64,linux/arm64
      push:
        type: boolean
        default: false
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Short Commit Hash
        id: git_commit
        run: echo "short_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # The name of the person or app that initiated the workflow. For example, octocat.
          password: ${{ secrets.GITHUB_TOKEN }} # automatically provided by GitHub Actions, so you don't need to create it manually.

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ inputs.platforms }}
          context: .
          push: ${{ inputs.push }}
          # GITHUB_REPOSITORY = The owner and repository name. For example, octocat/Hello-World.
          # ghcr.io prefix makes sure we are pushing to GHCR
          tags: ghcr.io/${{ github.repository }}:latest , ghcr.io/${{ github.repository }}:${{ steps.git_commit.outputs.short_hash }} # octocat/Hello-World:ffac537

      - name: Post cleanup
        run: docker image prune -f
