name: Dry Run Kubernetes Apply

on:
  workflow_call:
    
jobs:
  dry-run-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Update deployment manifest
        if: ${{ hashFiles('k8s/deployment.yaml') != '' }}
        run: sed -i 's|CONTAINER_IMAGE|ghcr.io/${{ github.repository }}:latest|g' k8s/deployment.yaml
      
      - name: Show deployment manifest after update
        if: ${{ hashFiles('k8s/deployment.yaml') != '' && vars.PIPELINE_DEBUG == 'true' }}
        run: cat k8s/deployment.yaml

      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      
      - name: Start minikube
        run: minikube start
      
      - name: Generate configmap
        if: ${{ hashFiles('.env') != '' }}
        run: kubectl create configmap ${{ github.event.repository.name }}-config --from-env-file .env -o yaml --dry-run=client

      - name: Dry run deployment
        if: ${{ hashFiles('k8s/deployment.yaml') != '' }}
        run: kubectl apply -f k8s/deployment.yaml --dry-run=client

      - name: Dry run service
        if: ${{ hashFiles('k8s/service.yaml') != '' }}
        run: kubectl apply -f k8s/service.yaml --dry-run=client
