name: Dry Run Kubernetes Apply

on:
  workflow_call:
    inputs:
      env_files:
        type: string
        default: .env
    
jobs:
  dry-run-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate configmap without secrets
        uses: jabez007/create-express-template/.github/shared/kubernetes/manifests/configmap@development
        with:
          env_files: .env.common , .env.development
          debug: ${{ vars.pipeline_debug }}

      - uses: jabez007/create-express-template/.github/shared/kubernetes/manifests/deployment@development
        with:
          container_registry: ghcr.io
          image_tag: latest
          debug: ${{ vars.pipeline_debug }}
    
      - name: Install minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
      
      - name: Start minikube
        run: minikube start

      - uses: jabez007/create-express-template/.github/shared/kubernetes/apply@development
        with:
          debug: ${{ vars.pipeline_debug }}
