name: Run Shared Test Workflow

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run_tests:
    uses: jabez007/create-node-template/.github/workflows/shared.test.yml@master
    secrets: inherit

  test_docker:
    uses: jabez007/create-express-template/.github/workflows/shared.build_and_test.yml@development
    secrets: inherit
